name: needit_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # المكتبات الأساسية (التي يحتاجها التطبيق ليعمل)
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  flutter_bloc: ^8.1.6
  dio: ^5.5.0+1
  get_it: ^7.7.0
  shared_preferences: ^2.3.2
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  equatable: ^2.0.5
  
  # مكتبات الواجهة والرسوميات
  smooth_page_indicator: ^1.2.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flutter_verification_code: ^1.1.7
  text_scroll: ^0.2.0
  lottie: ^3.1.3
  image_picker: ^1.1.2
  modal_progress_hud_nsn: ^0.5.1
  cloud_firestore: ^6.1.2
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # إعدادات ملفات الـ Assets
  assets:
    - assets/images/
    - assets/home_categories_response.json
    - assets/Logo-6-[remix].json
    - assets/Logo-6-[remix]_light.json
    - assets/products_of_category.json